Docker
Murali-group/PathLinker pull request #13
Opened 2020-08-19 20:14 UTC by ajshedivy

The goal is to "dockerize" pathlinker. Follow the instructions in the readme to build the pathlinker image

2020-08-19 22:25 UTC, agitter requested changes
@ajshedivy and I have been discussing different versions of the Dockerfile, and this version looked good to me.  There is one residual comment in the readme that can be deleted.

We also experimented with Docker operations in GitHub Actions continuous integration.  By adding a [workflow file](https://github.com/agitter/PathLinker/blob/1420c7f95786d88a5106d2bc2abb857deb8583ca/.github/workflows/docker.yaml), GitHub can automatically [build](https://github.com/agitter/PathLinker/runs/974090584#step:4:1) the Docker image every time the repository is updated.  It can also automatically tag the image and deploy it to DockerHub.  That isn't necessary now but could be considered in the future.

2020-08-19 22:25 UTC, agitter commented on docker/README.md
> +
```suggestion
```
This may have been left over from an earlier version and can be deleted.

2020-08-24 21:23 UTC, ajshedivy commented
RE: running the docker container on the example data.

In order to run the container, use the command 
```
To run in Git for Windows and mount the example data inside the container:

winpty docker run -v /$(pwd)/example:/home/PathLinker/example -it pathlinker/pathlinker bash

then inside the container in the /home/Pathlinker/example directory call:

python ../run.py sample-in-net.txt sample-in-nodetypes.txt
```

The first command starts the container and opens up an interactive bash. Once the docker container is running move into the example directory (`/home/PathLinker/example`) and then call the second command to produce the `outk-100-ranked-edges.txt` file. This file should show up in the local example directory within the Pathlinker repository  since with used the `-v` flag.

2020-08-27 12:50 UTC, agitter commented on docker/README.md
> +- Build Pathlinker docker container
May want to keep the capitalization consistent in these lines: `PathLinker`

2020-08-27 12:52 UTC, agitter commented on docker/README.md
> +**Note the** `winpty` **cammand**
```suggestion
**Note the** `winpty` **command**
```

2020-08-28 00:53 UTC, merged